name : react-app
on:
  push:
    branches: [master]
jobs:
  runs-on: ubuntu-latest 
  strategy: 
    matrix: 
      node-version: [14.x , 16.x , 18.x]
  steps:
    - uses: actions/checkout@v3
    - name: use nodejs ${{matrix.node-version}}
      uses: actions/setup-node@v3
      with: 
        node-version: ${{matrix.node-version}}
        cache: npm 
    - run: npm install 
     